### ISSUE TITLE
Celery > PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.4/dist-packages/trigger_happy.log'

### ISSUE THREAD

**Issue by nsteinmetz** [foxmask/django-th#121]
When I run manually the command from my th root folder, I have:

```
$ /usr/local/bin/celery -A django_th worker --autoscale=10,3 -l info
Traceback (most recent call last):
  File "/usr/lib/python3.4/logging/config.py", line 557, in configure
    handler = self.configure_handler(handlers[name])
  File "/usr/lib/python3.4/logging/config.py", line 725, in configure_handler
    result = factory(**kwargs)
  File "/usr/lib/python3.4/logging/handlers.py", line 150, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python3.4/logging/handlers.py", line 57, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python3.4/logging/__init__.py", line 1006, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.4/logging/__init__.py", line 1030, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.4/dist-packages/trigger_happy.log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/celery/__main__.py", line 30, in main
    main()
  File "/usr/local/lib/python3.4/dist-packages/celery/bin/celery.py", line 81, in main
    cmd.execute_from_commandline(argv)
  File "/usr/local/lib/python3.4/dist-packages/celery/bin/celery.py", line 770, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/usr/local/lib/python3.4/dist-packages/celery/bin/base.py", line 311, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/usr/local/lib/python3.4/dist-packages/celery/bin/celery.py", line 762, in handle_argv
    return self.execute(command, argv)
  File "/usr/local/lib/python3.4/dist-packages/celery/bin/celery.py", line 694, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/usr/local/lib/python3.4/dist-packages/celery/bin/worker.py", line 179, in run_from_argv
    return self(*args, **options)
  File "/usr/local/lib/python3.4/dist-packages/celery/bin/base.py", line 274, in __call__
    ret = self.run(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/celery/bin/worker.py", line 213, in run
    ).start()
  File "/usr/local/lib/python3.4/dist-packages/celery/worker/__init__.py", line 95, in __init__
    self.app.loader.init_worker()
  File "/usr/local/lib/python3.4/dist-packages/celery/loaders/base.py", line 128, in init_worker
    self.import_default_modules()
  File "/usr/local/lib/python3.4/dist-packages/celery/loaders/base.py", line 116, in import_default_modules
    signals.import_modules.send(sender=self.app)
  File "/usr/local/lib/python3.4/dist-packages/celery/utils/dispatch/signal.py", line 166, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/usr/local/lib/python3.4/dist-packages/celery/fixups/django.py", line 73, in on_import_modules
    self.worker_fixup.validate_models()
  File "/usr/local/lib/python3.4/dist-packages/celery/fixups/django.py", line 158, in validate_models
    django_setup()
  File "/usr/local/lib/python3.4/dist-packages/django/__init__.py", line 17, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/usr/local/lib/python3.4/dist-packages/django/utils/log.py", line 86, in configure_logging
    logging_config_func(logging_settings)
  File "/usr/lib/python3.4/logging/config.py", line 789, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib/python3.4/logging/config.py", line 565, in configure
    '%r: %s' % (name, e))
ValueError: Unable to configure handler 'file': [Errno 13] Permission denied: '/usr/local/lib/python3.4/dist-packages/trigger_happy.log'
```
I guess the settings part you mention about Celery is in th/settings.py. Is there something more to be done on Celery side ? Or a django-celery app maybe to make the bridge ?

**Comment by nsteinmetz** [comment]
If I do a symlink to the real trigger_happy.log, it now fails on cache dir:

```
 /usr/local/bin/celery -A django_th worker --autoscale=10,3 -l info
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/core/cache/backends/filebased.py", line 107, in _createdir
    os.makedirs(self._dir, 0o700)
  File "/usr/lib/python3.4/os.py", line 237, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.4/dist-packages/cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/celery/__main__.py", line 30, in main
    main()
  File "/usr/local/lib/python3.4/dist-packages/celery/bin/celery.py", line 81, in main
    cmd.execute_from_commandline(argv)
  File "/usr/local/lib/python3.4/dist-packages/celery/bin/celery.py", line 770, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/usr/local/lib/python3.4/dist-packages/celery/bin/base.py", line 311, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/usr/local/lib/python3.4/dist-packages/celery/bin/celery.py", line 762, in handle_argv
    return self.execute(command, argv)
  File "/usr/local/lib/python3.4/dist-packages/celery/bin/celery.py", line 694, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/usr/local/lib/python3.4/dist-packages/celery/bin/worker.py", line 179, in run_from_argv
    return self(*args, **options)
  File "/usr/local/lib/python3.4/dist-packages/celery/bin/base.py", line 274, in __call__
    ret = self.run(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/celery/bin/worker.py", line 213, in run
    ).start()
  File "/usr/local/lib/python3.4/dist-packages/celery/worker/__init__.py", line 100, in __init__
    self.setup_instance(**self.prepare_args(**kwargs))
  File "/usr/local/lib/python3.4/dist-packages/celery/worker/__init__.py", line 131, in setup_instance
    signals.worker_init.send(sender=self)
  File "/usr/local/lib/python3.4/dist-packages/celery/utils/dispatch/signal.py", line 166, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/usr/local/lib/python3.4/dist-packages/celery/fixups/django.py", line 76, in on_worker_init
    self.worker_fixup.install()
  File "/usr/local/lib/python3.4/dist-packages/celery/fixups/django.py", line 188, in install
    self.close_cache()
  File "/usr/local/lib/python3.4/dist-packages/celery/fixups/django.py", line 259, in close_cache
    self._cache.cache.close()
  File "/usr/local/lib/python3.4/dist-packages/django/core/cache/__init__.py", line 131, in __getattr__
    return getattr(caches[DEFAULT_CACHE_ALIAS], name)
  File "/usr/local/lib/python3.4/dist-packages/django/core/cache/__init__.py", line 113, in __getitem__
    cache = _create_cache(alias)
  File "/usr/local/lib/python3.4/dist-packages/django/core/cache/__init__.py", line 88, in _create_cache
    return backend_cls(location, params)
  File "/usr/local/lib/python3.4/dist-packages/django/core/cache/backends/filebased.py", line 28, in __init__
    self._createdir()
  File "/usr/local/lib/python3.4/dist-packages/django/core/cache/backends/filebased.py", line 112, in _createdir
    "and could not be created'" % self._dir)
OSError: Cache directory '/usr/local/lib/python3.4/dist-packages/cache' does not exist and could not be created'
```

Seems I missed something to make celery aware of django context ?!

**Comment by foxmask** [comment]
the settings about the logfile is define like this https://github.com/foxmask/django-th/blob/master/django_th/settings.py#L171-L179

the settings about the cache is defined like this https://github.com/foxmask/django-th/blob/master/django_th/settings.py#L198-L205

I have to check if I use it or not, I dont think so.
At the beginning of the projet may be.

May be it could be use in the FeedParser again. But on trigger-happy.eu the folder is empy.

**Comment by nsteinmetz** [comment]
In previous version /cache/rss was populated ; what I don't understand is that in django settings.py, logging is correctly define but seems Celery cannot use it properly and then falls back to /usr/local/lib/python3.4/dist-packages/ instead of /srv/web/steinmetz.fr/th for me.

**Comment by nsteinmetz** [comment]
Is the settings.py from django-th evaluated ? As I installed it from pip, its base_dir is /usr/local/lib/python3.4/dist-packages/ as withing my project, it's /srv/web/steinmetz.fr/th. Maybe there is a collision.

I guess you do not have the collision if the django-th is cloned via github as it's in your project folder.

I'll try tonight to rename the variable to see if it improves things or not.

**Comment by foxmask** [comment]
To setup Celery with django properly you need this : 

* https://github.com/foxmask/django-th/blob/master/django_th/celery.py
* https://github.com/foxmask/django-th/blob/master/django_th/apps.py#L4
* https://github.com/foxmask/django-th/blob/master/django_th/celery.py#L4

You can have a look at https://celery.readthedocs.org/en/latest/django/first-steps-with-django.html?highlight=django

Here we put "from .celery import app as celery_app" in apps.py instead of __init__.py like the doc of celery says

**Comment by nsteinmetz** [comment]
Will do it this evening - thanks !

So it should be mentionned in the docs too for people who are not familiar with Celery ;)

**Comment by foxmask** [comment]
after checking my site trigger-happy.eu, I just create the celery.py file and add "from .celery import app as celery_app" in the _init__.py` file of my root installation ;)

**Comment by foxmask** [comment]
about the launching of the worker, I made several tests, and autoscale should not be used because of an annoying error. So in the next release I will drop it
so instead of 

    celery -A django_th worker --autoscale=10,3 -l info

will become

    celery -A django_th worker -l info

**Comment by nsteinmetz** [comment]
Ok so it works once apps.py is defined and with latest statement ``celery -A <app_name> worker -l info``

Should be documented !

Thanks !

**Comment by nsteinmetz** [comment]
```
[2015-11-17 21:59:00,045: INFO/MainProcess] Scheduler: Sending due task read-data (django_th.tasks.read_data)
[2015-11-17 21:59:00,048: INFO/MainProcess] Received task: django_th.tasks.read_data[2b5b9b3b-0d6e-462d-a1df-eee66f0806d7]
[2015-11-17 21:59:00,094: INFO/MainProcess] Received task: django_th.tasks.put_in_cache[84c4107c-1cf0-432c-8d7f-1de07320e8b5]
[2015-11-17 21:59:00,097: INFO/MainProcess] Received task: django_th.tasks.put_in_cache[d67706fe-1bc3-408d-8af9-33f52caf0c06]
[2015-11-17 21:59:00,099: INFO/MainProcess] Received task: django_th.tasks.put_in_cache[d9873024-7f82-46d5-bcb5-77a5efbae701]
[2015-11-17 21:59:00,099: INFO/MainProcess] Task django_th.tasks.read_data[2b5b9b3b-0d6e-462d-a1df-eee66f0806d7] succeeded in 0.04939943899807986s: None
[2015-11-17 21:59:00,101: INFO/MainProcess] Received task: django_th.tasks.put_in_cache[1ed14bdb-43de-4232-a084-e8ac0d684609]
INFO user: nsteinmetz - provider: ServiceRss - Tweet tutorials nothing new
[2015-11-17 21:59:00,191: INFO/Worker-2] user: nsteinmetz - provider: ServiceRss - Tweet tutorials nothing new
[2015-11-17 21:59:00,194: INFO/MainProcess] Task django_th.tasks.put_in_cache[84c4107c-1cf0-432c-8d7f-1de07320e8b5] succeeded in 0.09606284199981019s: None
INFO user: nsteinmetz - provider: ServiceRss - Tweet blog posts - 20 data put in cache
[2015-11-17 21:59:00,386: INFO/Worker-1] user: nsteinmetz - provider: ServiceRss - Tweet blog posts - 20 data put in cache
[2015-11-17 21:59:00,388: INFO/MainProcess] Task django_th.tasks.put_in_cache[d67706fe-1bc3-408d-8af9-33f52caf0c06] succeeded in 0.2861607520026155s: None
INFO user: nsteinmetz - provider: ServiceRss - Tweet Web Enthusiasts blog posts - 20 data put in cache
[2015-11-17 21:59:00,643: INFO/Worker-1] user: nsteinmetz - provider: ServiceRss - Tweet Web Enthusiasts blog posts - 20 data put in cache
[2015-11-17 21:59:00,645: INFO/MainProcess] Task django_th.tasks.put_in_cache[1ed14bdb-43de-4232-a084-e8ac0d684609] succeeded in 0.25558676999935415s: None
INFO user: nsteinmetz - provider: ServiceRss - Tweet shared feed from tt-rss nothing new
[2015-11-17 21:59:00,747: INFO/Worker-2] user: nsteinmetz - provider: ServiceRss - Tweet shared feed from tt-rss nothing new
[2015-11-17 21:59:00,748: INFO/MainProcess] Task django_th.tasks.put_in_cache[d9873024-7f82-46d5-bcb5-77a5efbae701] succeeded in 0.5525640580017352s: None
```
So far so good :)

**Comment by nsteinmetz** [comment]
Grrr:

```
2015-11-17 22:15:00,084: INFO/MainProcess] Scheduler: Sending due task publish-data (django_th.tasks.publish_data)
[2015-11-17 22:15:00,086: INFO/MainProcess] Received task: django_th.tasks.publish_data[f734df8a-6503-46ed-9810-c32c8670bdad]
[2015-11-17 22:15:00,104: ERROR/MainProcess] Task django_th.tasks.publish_data[f734df8a-6503-46ed-9810-c32c8670bdad] raised unexpected: TypeError("object of type 'NoneType' has no len()",)
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django_th/tasks.py", line 158, in publish_data
    datas = getattr(service_provider, 'process_data')(service.id)
  File "/usr/local/lib/python3.4/dist-packages/th_rss/my_rss.py", line 85, in process_data
    return PublishingLimit.get_data('th_rss', cache_data, trigger_id)
  File "/usr/local/lib/python3.4/dist-packages/django_th/publishing_limit.py", line 41, in get_data
    if len(cache_data) > limit:
TypeError: object of type 'NoneType' has no len()
```

**Comment by nsteinmetz** [comment]
Si ça peut aider:

![redis0](https://cloud.githubusercontent.com/assets/33180/11225186/16ac6d46-8d79-11e5-8749-40d828142c5d.png)

**Comment by nsteinmetz** [comment]
Seems two feeds are well interpreted but two are never stored as they seems refreshed:

```
[2015-11-17 22:30:00,091: INFO/MainProcess] Scheduler: Sending due task read-data (django_th.tasks.read_data)
[2015-11-17 22:30:00,093: INFO/MainProcess] Received task: django_th.tasks.read_data[76eac3c9-c12d-4892-9ad3-a5cb6a651876]
[2015-11-17 22:30:00,109: INFO/MainProcess] Received task: django_th.tasks.put_in_cache[dc1baa7c-20d8-407c-89eb-dc8c6ee8d387]
[2015-11-17 22:30:00,111: INFO/MainProcess] Received task: django_th.tasks.put_in_cache[fc6e0ed1-d208-4398-ae2d-0bd411563b8b]
[2015-11-17 22:30:00,115: INFO/MainProcess] Received task: django_th.tasks.put_in_cache[26289d68-bca9-4956-855b-9e60c3e61808]
[2015-11-17 22:30:00,116: INFO/MainProcess] Task django_th.tasks.read_data[76eac3c9-c12d-4892-9ad3-a5cb6a651876] succeeded in 0.02236333400651347s: None
[2015-11-17 22:30:00,117: INFO/MainProcess] Received task: django_th.tasks.put_in_cache[9fc572ca-5aec-4ad2-842f-c3c41f1d712a]
INFO user: nsteinmetz - provider: ServiceRss - Tweet tutorials nothing new
[2015-11-17 22:30:00,193: INFO/Worker-1] user: nsteinmetz - provider: ServiceRss - Tweet tutorials nothing new
[2015-11-17 22:30:00,196: INFO/MainProcess] Task django_th.tasks.put_in_cache[dc1baa7c-20d8-407c-89eb-dc8c6ee8d387] succeeded in 0.08433863100071903s: None
INFO user: nsteinmetz - provider: ServiceRss - Tweet blog posts - 20 data put in cache
[2015-11-17 22:30:00,399: INFO/Worker-2] user: nsteinmetz - provider: ServiceRss - Tweet blog posts - 20 data put in cache
[2015-11-17 22:30:00,402: INFO/MainProcess] Task django_th.tasks.put_in_cache[fc6e0ed1-d208-4398-ae2d-0bd411563b8b] succeeded in 0.2841008130053524s: None
INFO user: nsteinmetz - provider: ServiceRss - Tweet Web Enthusiasts blog posts - 20 data put in cache
[2015-11-17 22:30:00,652: INFO/Worker-2] user: nsteinmetz - provider: ServiceRss - Tweet Web Enthusiasts blog posts - 20 data put in cache
[2015-11-17 22:30:00,655: INFO/MainProcess] Task django_th.tasks.put_in_cache[9fc572ca-5aec-4ad2-842f-c3c41f1d712a] succeeded in 0.25163688701286446s: None
INFO user: nsteinmetz - provider: ServiceRss - Tweet shared feed from tt-rss nothing new
[2015-11-17 22:30:00,763: INFO/Worker-1] user: nsteinmetz - provider: ServiceRss - Tweet shared feed from tt-rss nothing new
[2015-11-17 22:30:00,765: INFO/MainProcess] Task django_th.tasks.put_in_cache[26289d68-bca9-4956-855b-9e60c3e61808] succeeded in 0.5676795990002574s: None
```

**Comment by nsteinmetz** [comment]
With the publish_limit=0 or some chance, then the *:th_rss* keys are populated whereas it was none before.

**Comment by nsteinmetz** [comment]
So issue seems related to publish_limit as when it's equal to 0:

```
[2015-11-17 22:59:00,065: INFO/MainProcess] Scheduler: Sending due task read-data (django_th.tasks.read_data)
[2015-11-17 22:59:00,069: INFO/MainProcess] Received task: django_th.tasks.read_data[bc5ff3f9-1657-4685-a585-131fb9e5eb1a]
[2015-11-17 22:59:00,114: INFO/MainProcess] Received task: django_th.tasks.put_in_cache[304d44fd-4faf-4756-91fc-ce722afa8100]
[2015-11-17 22:59:00,118: INFO/MainProcess] Received task: django_th.tasks.put_in_cache[78b360e5-f9a0-4ade-bf6a-bd751784dd58]
[2015-11-17 22:59:00,124: INFO/MainProcess] Received task: django_th.tasks.put_in_cache[23bf4d2c-90aa-484c-8e59-c9e74f42aaeb]
[2015-11-17 22:59:00,125: INFO/MainProcess] Task django_th.tasks.read_data[bc5ff3f9-1657-4685-a585-131fb9e5eb1a] succeeded in 0.05440438899677247s: None
[2015-11-17 22:59:00,126: INFO/MainProcess] Received task: django_th.tasks.put_in_cache[04bc8b39-1068-459e-a749-9ef2e5c36920]
INFO user: nsteinmetz - provider: ServiceRss - Tweet tutorials nothing new
[2015-11-17 22:59:00,212: INFO/Worker-2] user: nsteinmetz - provider: ServiceRss - Tweet tutorials nothing new
[2015-11-17 22:59:00,215: INFO/MainProcess] Task django_th.tasks.put_in_cache[304d44fd-4faf-4756-91fc-ce722afa8100] succeeded in 0.09677527300664224s: None
INFO user: nsteinmetz - provider: ServiceRss - Tweet blog posts - 20 data put in cache
[2015-11-17 22:59:00,412: INFO/Worker-1] user: nsteinmetz - provider: ServiceRss - Tweet blog posts - 20 data put in cache
[2015-11-17 22:59:00,415: INFO/MainProcess] Task django_th.tasks.put_in_cache[78b360e5-f9a0-4ade-bf6a-bd751784dd58] succeeded in 0.28757104999385774s: None
INFO user: nsteinmetz - provider: ServiceRss - Tweet Web Enthusiasts blog posts - 20 data put in cache
[2015-11-17 22:59:00,671: INFO/Worker-1] user: nsteinmetz - provider: ServiceRss - Tweet Web Enthusiasts blog posts - 20 data put in cache
[2015-11-17 22:59:00,674: INFO/MainProcess] Task django_th.tasks.put_in_cache[04bc8b39-1068-459e-a749-9ef2e5c36920] succeeded in 0.2580688689922681s: None
INFO user: nsteinmetz - provider: ServiceRss - Tweet shared feed from tt-rss nothing new
[2015-11-17 22:59:00,777: INFO/Worker-2] user: nsteinmetz - provider: ServiceRss - Tweet shared feed from tt-rss nothing new
[2015-11-17 22:59:00,779: INFO/MainProcess] Task django_th.tasks.put_in_cache[23bf4d2c-90aa-484c-8e59-c9e74f42aaeb] succeeded in 0.5629709519998869s: None
[2015-11-17 23:10:00,045: INFO/MainProcess] Scheduler: Sending due task read-data (django_th.tasks.read_data)
[2015-11-17 23:10:00,047: INFO/MainProcess] Received task: django_th.tasks.read_data[e94dacec-6c8f-4876-a54e-63d332f5313c]
[2015-11-17 23:10:00,083: INFO/MainProcess] Received task: django_th.tasks.put_in_cache[23287106-3375-4103-b587-e71ae3203c89]
[2015-11-17 23:10:00,084: INFO/MainProcess] Received task: django_th.tasks.put_in_cache[5307cab4-be18-4b23-9cd2-6acd0780a8b6]
[2015-11-17 23:10:00,087: INFO/MainProcess] Received task: django_th.tasks.put_in_cache[ae68f695-7a57-4a9b-bc5e-53b0a17bfd2d]
[2015-11-17 23:10:00,089: INFO/MainProcess] Received task: django_th.tasks.put_in_cache[43bbf501-b463-40e5-a44d-86b9e587de70]
[2015-11-17 23:10:00,091: INFO/MainProcess] Task django_th.tasks.read_data[e94dacec-6c8f-4876-a54e-63d332f5313c] succeeded in 0.043184644004213624s: None
INFO user: nsteinmetz - provider: ServiceRss - Tweet tutorials nothing new
[2015-11-17 23:10:00,167: INFO/Worker-1] user: nsteinmetz - provider: ServiceRss - Tweet tutorials nothing new
[2015-11-17 23:10:00,170: INFO/MainProcess] Task django_th.tasks.put_in_cache[23287106-3375-4103-b587-e71ae3203c89] succeeded in 0.08547256000747439s: None
INFO user: nsteinmetz - provider: ServiceRss - Tweet blog posts - 20 data put in cache
[2015-11-17 23:10:00,376: INFO/Worker-2] user: nsteinmetz - provider: ServiceRss - Tweet blog posts - 20 data put in cache
[2015-11-17 23:10:00,379: INFO/MainProcess] Task django_th.tasks.put_in_cache[5307cab4-be18-4b23-9cd2-6acd0780a8b6] succeeded in 0.2870174239942571s: None
INFO user: nsteinmetz - provider: ServiceRss - Tweet Web Enthusiasts blog posts - 20 data put in cache
[2015-11-17 23:10:00,632: INFO/Worker-2] user: nsteinmetz - provider: ServiceRss - Tweet Web Enthusiasts blog posts - 20 data put in cache
[2015-11-17 23:10:00,633: INFO/MainProcess] Task django_th.tasks.put_in_cache[43bbf501-b463-40e5-a44d-86b9e587de70] succeeded in 0.253263706996222s: None
INFO user: nsteinmetz - provider: ServiceRss - Tweet shared feed from tt-rss nothing new
[2015-11-17 23:10:00,740: INFO/Worker-1] user: nsteinmetz - provider: ServiceRss - Tweet shared feed from tt-rss nothing new
[2015-11-17 23:10:00,741: INFO/MainProcess] Task django_th.tasks.put_in_cache[ae68f695-7a57-4a9b-bc5e-53b0a17bfd2d] succeeded in 0.5704701040085638s: None
[2015-11-17 23:15:00,060: INFO/MainProcess] Scheduler: Sending due task publish-data (django_th.tasks.publish_data)
[2015-11-17 23:15:00,062: INFO/MainProcess] Received task: django_th.tasks.publish_data[32a19a42-932e-4ede-af11-1296c9ab72a5]
INFO user: nsteinmetz - provider: ServiceRss - consumer: ServiceTwitter - Tweet blog posts nothing new
[2015-11-17 23:15:00,098: INFO/Worker-1] user: nsteinmetz - provider: ServiceRss - consumer: ServiceTwitter - Tweet blog posts nothing new
INFO user: nsteinmetz - provider: ServiceRss - consumer: ServiceTwitter - Tweet Web Enthusiasts blog posts nothing new
[2015-11-17 23:15:00,118: INFO/Worker-1] user: nsteinmetz - provider: ServiceRss - consumer: ServiceTwitter - Tweet Web Enthusiasts blog posts nothing new
[2015-11-17 23:15:00,119: INFO/MainProcess] Task django_th.tasks.publish_data[32a19a42-932e-4ede-af11-1296c9ab72a5] succeeded in 0.05615276900061872s: None
```
