### ISSUE TITLE
Evernote should not be required if not used

### ISSUE THREAD

**Issue by nsteinmetz** [foxmask/django-th#122]
I was surprised to see:

```
/usr/local/bin/celery -A django_th worker --autoscale=10,3 -l info
Traceback (most recent call last):
  File "/usr/local/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/celery/__main__.py", line 30, in main
    main()
  File "/usr/local/lib/python3.4/dist-packages/celery/bin/celery.py", line 81, in main
    cmd.execute_from_commandline(argv)
  File "/usr/local/lib/python3.4/dist-packages/celery/bin/celery.py", line 770, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/usr/local/lib/python3.4/dist-packages/celery/bin/base.py", line 311, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/usr/local/lib/python3.4/dist-packages/celery/bin/celery.py", line 762, in handle_argv
    return self.execute(command, argv)
  File "/usr/local/lib/python3.4/dist-packages/celery/bin/celery.py", line 694, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/usr/local/lib/python3.4/dist-packages/celery/bin/worker.py", line 179, in run_from_argv
    return self(*args, **options)
  File "/usr/local/lib/python3.4/dist-packages/celery/bin/base.py", line 274, in __call__
    ret = self.run(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/celery/bin/worker.py", line 213, in run
    ).start()
  File "/usr/local/lib/python3.4/dist-packages/celery/worker/__init__.py", line 95, in __init__
    self.app.loader.init_worker()
  File "/usr/local/lib/python3.4/dist-packages/celery/loaders/base.py", line 128, in init_worker
    self.import_default_modules()
  File "/usr/local/lib/python3.4/dist-packages/celery/loaders/base.py", line 116, in import_default_modules
    signals.import_modules.send(sender=self.app)
  File "/usr/local/lib/python3.4/dist-packages/celery/utils/dispatch/signal.py", line 166, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/usr/local/lib/python3.4/dist-packages/amqp/utils.py", line 42, in __call__
    self.set_error_state(exc)
  File "/usr/local/lib/python3.4/dist-packages/amqp/utils.py", line 39, in __call__
    **dict(self.kwargs, **kwargs) if self.kwargs else kwargs
  File "/usr/local/lib/python3.4/dist-packages/celery/app/base.py", line 330, in _autodiscover_tasks
    self.loader.autodiscover_tasks(packages, related_name)
  File "/usr/local/lib/python3.4/dist-packages/celery/loaders/base.py", line 251, in autodiscover_tasks
    related_name) if mod)
  File "/usr/local/lib/python3.4/dist-packages/celery/loaders/base.py", line 272, in autodiscover_tasks
    return [find_related_module(pkg, related_name) for pkg in packages]
  File "/usr/local/lib/python3.4/dist-packages/celery/loaders/base.py", line 272, in <listcomp>
    return [find_related_module(pkg, related_name) for pkg in packages]
  File "/usr/local/lib/python3.4/dist-packages/celery/loaders/base.py", line 298, in find_related_module
    return importlib.import_module('{0}.{1}'.format(package, related_name))
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/usr/local/lib/python3.4/dist-packages/django_th/tasks.py", line 20, in <module>
    default_provider.load_services()
  File "/usr/local/lib/python3.4/dist-packages/django_th/service_provider.py", line 14, in load_services
    klass = import_from_path(class_path)
  File "/usr/local/lib/python3.4/dist-packages/django_th/service_provider.py", line 39, in import_from_path
    fromlist=[class_name]), class_name)
  File "/usr/local/lib/python3.4/dist-packages/th_evernote/my_evernote.py", line 8, in <module>
    from evernote.api.client import EvernoteClient
ImportError: No module named 'evernote'
```

Installing evernote is fine then but it should not be required if not used (and not used in my context)

**Comment by foxmask** [comment]
I searched a way to deal with the module we want to use, I found this :  

https://github.com/crossbario/crossbar/blob/master/setup.py#L152-L162

to be able to make his receipe :)


    pip install django-trigger-happy[all]
    pip install django-trigger-happy[rss,pocket]
    pip install django-trigger-happy[rss,twitter,pocket,github]

and so on
