### ISSUE TITLE
Error when publish_limit is no longer equal to 0

### ISSUE THREAD

**Issue by nsteinmetz** [foxmask/django-th#124]
Seen in #121 ; if publish_limit is not equal to 0, then error is raised 

```
2015-11-17 22:15:00,084: INFO/MainProcess] Scheduler: Sending due task publish-data (django_th.tasks.publish_data)
[2015-11-17 22:15:00,086: INFO/MainProcess] Received task: django_th.tasks.publish_data[f734df8a-6503-46ed-9810-c32c8670bdad]
[2015-11-17 22:15:00,104: ERROR/MainProcess] Task django_th.tasks.publish_data[f734df8a-6503-46ed-9810-c32c8670bdad] raised unexpected: TypeError("object of type 'NoneType' has no len()",)
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django_th/tasks.py", line 158, in publish_data
    datas = getattr(service_provider, 'process_data')(service.id)
  File "/usr/local/lib/python3.4/dist-packages/th_rss/my_rss.py", line 85, in process_data
    return PublishingLimit.get_data('th_rss', cache_data, trigger_id)
  File "/usr/local/lib/python3.4/dist-packages/django_th/publishing_limit.py", line 41, in get_data
    if len(cache_data) > limit:
TypeError: object of type 'NoneType' has no len()
```

**Comment by foxmask** [comment]
if that concerns a new trigger, click on the button "off" then reclick on "on" this will set a trigger date otherwise right now I put 0 to the limit and could flood trello :)

**Comment by nsteinmetz** [comment]
I give it up - seems my two instances are messy (the old one upgraded or the new one from scratch). Wil check it later.
