### ISSUE TITLE
When running migrate for the first time: ImportError: No module named 'environ'

### ISSUE THREAD

**Issue by lambsteak** [foxmask/django-th#266]
I just cloned the repo and installed all the dependencies in the virtualenv. When I ran the migrate command I got the following traceback:
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/fries/projects/django-th/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/fries/projects/django-th/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/home/fries/projects/django-th/venv/lib/python3.5/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/home/fries/projects/django-th/venv/lib/python3.5/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/fries/projects/django-th/venv/lib/python3.5/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/fries/projects/django-th/venv/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/fries/projects/django-th/django-th/django_th/th_settings.py", line 1, in <module>
    from .settings import *  # noqa
  File "/home/fries/projects/django-th/django-th/django_th/settings.py", line 5, in <module>
    import environ
ImportError: No module named 'environ'
```

**Comment by lambsteak** [comment]
I'm using the default settings (ie, whatever the repo came with) and I cloned from the repo's main branch and my Python version is 3.5.2

**Comment by foxmask** [comment]
Hi,
I suppose you did:
```
python setup.py install 
```
try with 
```
pip install -r requirements.txt
```
I am going to fix the missing django-environ from setup.py

**Comment by foxmask** [comment]
97dfa0918a476940bbb6a19ac990dd3320f7b2f6
